baseURL = "https://jav-car-1971.github.io/francaise/"
languageCode = "fr-fr" # languageCode = "es-es" Le cambié el idioma a la configuración.
title = "Mon blog en français"
theme = "PaperMod"

enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true
disableScrollToTop = true

[outputs]
  home = ["HTML", "RSS", "JSON"] # Para búsqueda

[minify]
  disableXML = true
  disableHTML = true

[params]
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionPage = true
  disableSpecial1stPost = false
  disableAnchoredHeadings = false
  disableHeadingEmoji = false
  hideSummary = false
  disableHugoGeneratorInject = false

#[params.homeInfoParams]
 # Title = "¡Bonjour! 👋"
 # Content = "Bienvenue sur mon blog français."
